apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.minio-dev.namespace }}
spec:
  type: {{ .Values.minio.serviceType }}
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9090
    protocol: TCP
    targetPort: 9090

