apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: {{ .Values.minio-dev.namespace }}
spec:
  containers:
  - name: minio
    image: {{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}
    command:
    - /bin/bash
    - -c
    args:
    - minio server /export --console-address :9090
    ports:
    - containerPort: 9000
    - containerPort: 9090
    volumeMounts:
    - mountPath: /export
      name: localvolume
  volumes:
  - name: localvolume
    hostPath:
      path: /home/rsingh2/git/accumulo-examples/helm/accumulo/export
      type: DirectoryOrCreate

